### ISSUE TITLE
if autoStart is false then how to start the animation

### ISSUE THREAD

**Issue by areebvohra** [booncol/pulsator#1]
I tried to start the animation on button press but I can't find any documentation on how to start the animation if the autoStart property is false.

**Comment by booncol** [comment]
To start the animation manually, you need to capture the `AnimationController` from the Pulsator widget. This is possible using the `onCreated` event:

```dart
Pulsator(
   ...
   onCreated: (controller) => _controller = controller,
),
```

then to start the animation call:

```dart
_controller.forward();
```
